/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.16
 * Generated at: 2023-12-01 02:11:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!--%\r\n");
      out.write("    if(session.getAttribute(\"email\") == null){\r\n");
      out.write("        response.sendRedirect(\"login.jsp\");\r\n");
      out.write("    }\r\n");
      out.write("%-->\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp", out, false);
      out.write("\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("<main>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"myCarousel\" class=\"carousel slide mb-4\" data-bs-ride=\"carousel\">\r\n");
      out.write("        <div class=\"carousel-indicators\">\r\n");
      out.write("            <button type=\"button\" data-bs-target=\"#myCarousel\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\"\r\n");
      out.write("                aria-label=\"Slide 1\"></button>\r\n");
      out.write("            <button type=\"button\" data-bs-target=\"#myCarousel\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("            <button type=\"button\" data-bs-target=\"#myCarousel\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-inner\">\r\n");
      out.write("            <div class=\"carousel-item active bg-carousel-ba1\">\r\n");
      out.write("                <svg class=\"bd-placeholder-img\" width=\"100%\" height=\"100%\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><rect width=\"100%\" height=\"100%\" fill=\"#000\"/></svg>\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"carousel-caption text-end pb-5\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-lg-8 offset-lg-6\">\r\n");
      out.write("                                <h3>Conf Bs. As</h3>\r\n");
      out.write("                                <p>Bs. As. llega por primera vez a la Argentina. Un evento para compartir con nuestra comunidad el conocimiento y la experiencia de los expertos que están creando el futuro de internet. Ven a conocer a miembros del evento, a otros estudiantes de Codo a Codo y a los oradores de primer nivel que tenemos para ti. Te esperamos!</p>\r\n");
      out.write("                                <p><a class=\"btn btn-outline-light mb-3\" href=\"#form-orador\">Quiero ser orador</a> <a class=\"btn btn-success ms-2 mb-3\" href=\"comprar-tickets.jsp\">Comprar tickets</a></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item bg-carousel-ba2\">\r\n");
      out.write("                <svg class=\"bd-placeholder-img\" width=\"100%\" height=\"100%\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><rect width=\"100%\" height=\"100%\" fill=\"#000\"/></svg>\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"carousel-caption text-end pb-5\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-lg-6 offset-lg-6\">\r\n");
      out.write("                                <h3>Conf Bs. As.</h3>\r\n");
      out.write("                                <p>Bs. As. llega por primera vez a la Argentina. Un evento para compartir con nuestra comunidad el conocimiento y la experiencia de los expertos que están creando el futuro de internet. Ven a conocer a miembros del evento, a otros estudiantes de Codo a Codo y a los oradores de primer nivel que tenemos para ti. Te esperamos!</p>\r\n");
      out.write("                                <p><a class=\"btn btn-outline-light mb-3\" href=\"#form-orador\">Quiero ser orador</a> <a class=\"btn btn-success ms-2 mb-3\" href=\"comprar-tickets.jsp\">Comprar tickets</a></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item bg-carousel-ba3\">\r\n");
      out.write("                <svg class=\"bd-placeholder-img\" width=\"100%\" height=\"100%\" xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" preserveAspectRatio=\"xMidYMid slice\" focusable=\"false\"><rect width=\"100%\" height=\"100%\" fill=\"#000\"/></svg>\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"carousel-caption text-end pb-5\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-lg-6 offset-lg-6\">\r\n");
      out.write("                                <h3>Conf Bs. As.</h3>\r\n");
      out.write("                                <p>Bs. As. llega por primera vez a la Argentina. Un evento para compartir con nuestra comunidad el conocimiento y la experiencia de los expertos que están creando el futuro de internet. Ven a conocer a miembros del evento, a otros estudiantes de Codo a Codo y a los oradores de primer nivel que tenemos para ti. Te esperamos!</p>\r\n");
      out.write("                                <p><a class=\"btn btn-outline-light mb-3\" href=\"#form-orador\">Quiero ser orador</a> <a class=\"btn btn-success ms-2 mb-3\" href=\"comprar-tickets.jsp\">Comprar tickets</a></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#myCarousel\" data-bs-slide=\"prev\">\r\n");
      out.write("            <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("            <span class=\"visually-hidden\">Anterior</span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#myCarousel\" data-bs-slide=\"next\">\r\n");
      out.write("            <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("            <span class=\"visually-hidden\">Siguiente</span>\r\n");
      out.write("        </button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");

        if(session.getAttribute("email") != null){
    
      out.write("\r\n");
      out.write("        <section class=\"text-center mb-4 mt-4\">\r\n");
      out.write("            <h1>Hola <span class=\"badge bg-secondary btn-log-reg\">");
      out.print( session.getAttribute("nombre") );
      out.write("</span></h1>\r\n");
      out.write("        </section>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"container mb-4\" id=\"oradores\">\r\n");
      out.write("        <h2 class=\"titulo-gral\">Conoce a los <span>oradores</span></h2>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-md-11\">\r\n");
      out.write("                <div class=\"row row-cols-1 row-cols-md-3 g-4\">\r\n");
      out.write("                    <div class=\"col\">\r\n");
      out.write("                        <div class=\"card h-100\">\r\n");
      out.write("                            <img src=\"img/steve-min.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <div class=\"mb-2\">\r\n");
      out.write("                                    <span class=\"badge bg-warning text-dark\">Javascript</span>\r\n");
      out.write("                                    <span class=\"badge bg-info\">React</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <h5 class=\"card-title\">Steve Jobs</h5>\r\n");
      out.write("                                <p class=\"card-text\">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Et aspernatur, sit dolorem officiis dolor, nobis sed labore non culpa dignissimos amet excepturi odit quis quos temporibus ut asperiores possimus. Veniam!</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col\">\r\n");
      out.write("                        <div class=\"card h-100\">\r\n");
      out.write("                            <img src=\"img/bill-min.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <div class=\"mb-2\">\r\n");
      out.write("                                    <span class=\"badge bg-warning text-dark\">Javascript</span>\r\n");
      out.write("                                    <span class=\"badge bg-info\">React</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <h5 class=\"card-title\">Bill Gates</h5>\r\n");
      out.write("                                <p class=\"card-text\">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Molestias, nostrum saepe et quaerat illo possimus provident laboriosam totam sunt magni recusandae eligendi optio earum quas ab omnis fuga molestiae corrupti.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col\">\r\n");
      out.write("                        <div class=\"card h-100\">\r\n");
      out.write("                            <img src=\"img/ada-min.jpeg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <div class=\"mb-2\">\r\n");
      out.write("                                    <span class=\"badge bg-secondary\">Negocios</span>\r\n");
      out.write("                                    <span class=\"badge bg-danger\">Startups</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <h5 class=\"card-title\">Ada Lovelace</h5>\r\n");
      out.write("                                <p class=\"card-text\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores, veniam eius excepturi sapiente eligendi quaerat soluta nihil iste vero sequi cum nam quibusdam quam voluptas consequuntur natus! Optio, perspiciatis velit.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"mb-4\" id=\"lugar\">\r\n");
      out.write("        <div class=\"row g-0\">\r\n");
      out.write("            <div class=\"col-md\">\r\n");
      out.write("                <img src=\"img/honolulu-min.jpg\" alt=\"Honolulu\" class=\"img-fluid\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md text-light bg-aside1\">\r\n");
      out.write("                <h2>Bs As - Octubre</h2>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. At placeat molestias vitae unde facere voluptatem minus voluptates commodi corrupti tenetur! Pariatur qui enim animi sapiente sed error similique molestiae ipsum! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, excepturi deleniti harum facilis id, a illo assumenda officiis illum praesentium eos. Qui laborum ratione in hic ducimus debitis voluptatum aperiam.</p>\r\n");
      out.write("                <a class=\"btn btn-outline-light\" href=\"#\">Conocé más</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"container\" id=\"form-orador\">\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-lg-8 col-xl-7\">\r\n");
      out.write("                <h2 class=\"titulo-gral\">Conviértete en un <span>orador</span></h2>\r\n");
      out.write("                <p class=\"text-center\">Anótate como orador para dar una charla ignite. Cuéntanos de qué quieres hablar!</p>\r\n");
      out.write("                <form action=\"\">\r\n");
      out.write("                    <div class=\"row gx-2\">\r\n");
      out.write("                        <div class=\"col-md mb-3\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"Nombre\" aria-label=\"Nombre\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md mb-3\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" placeholder=\"Apellido\" aria-label=\"Apellido\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col mb-3\">\r\n");
      out.write("                            <input type=\"email\" class=\"form-control\" placeholder=\"Email\" aria-label=\"Email\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col mb-3\">\r\n");
      out.write("                            <textarea class=\"form-control\" id=\"exampleFormControlTextarea1\" rows=\"4\"\r\n");
      out.write("                                placeholder=\"Sobre qué quieres hablar?\" required></textarea>\r\n");
      out.write("                            <div id=\"emailHelp\" class=\"form-text mb-3\">Recuerda incluir un título para tu charla.</div>\r\n");
      out.write("                            <div class=\"d-grid\">\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-lg btn-form\">Enviar</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
